Update push-trigger.yml
Signed-off-by: bn46 <147074924+bn46@users.noreply.github.com>

diff --git a/.github/workflows/push-trigger.yml b/.github/workflows/push-trigger.yml
--- a/.github/workflows/push-trigger.yml
+++ b/.github/workflows/push-trigger.yml
@@ -18,26 +18,35 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Test
-        env:
-          TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          TEST_SECRET: ${{ secrets.TEST_SECRET }}
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+
+      - name: Get PR author
+        id: author
+        run: echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
+
+      - name: Decode Slack Users Secret
+        id: slack_id
         run: |
-          echo ${#TEST_GITHUB_TOKEN}
-          echo ${#TEST_SECRET}
-          echo ${#SLACK_BOT_TOKEN}
+          # Decode the JSON string from the secret
+          SLACK_USERS_MAP="${{ secrets.SLACK_USERS_MAP }}"
+          # Use jq to extract the Slack ID corresponding to the GitHub username
+          SLACK_USER_ID=$(echo "$SLACK_USERS_MAP" | jq -r --arg github_user "${{ env.author }}" '.[$github_user]')
+          if [ -z "$SLACK_USER_ID" ] || [ "$SLACK_USER_ID" == "null" ]; then
+            echo "Slack user ID not found for GitHub user: ${{ env.author }}"
+            exit 1
+          fi
+          echo "SLACK_USER_ID=$SLACK_USER_ID" >> $GITHUB_ENV
+
       - name: Post to a Slack channel
         id: slack
         uses: slackapi/slack-github-action@v1.27.0
         with:
-          channel-id: 'U07QEJS9LM9'
+          channel-id: ${{ env.SLACK_USER_ID }}
           slack-message: |
             *GitHub Action Notification* :rocket:
             *Repository*: ${{ github.repository }}
             *Message*: ${{ github.event.head_commit.message || github.event.pull_request.title }}
             *Commit*: ${{ github.sha }}
-            *Author*: ${{ github.event.head_commit.author.name || github.event.pull_request.user.login }}
+            *Author*: ${{ github.event.pull_request.user.login }}
             *Action*: ${{ github.event.action }}
             *Event Name*: ${{ github.event_name }}
             *Branch (ref)*: ${{ github.ref }}
